repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: detect-aws-credentials
      - id: detect-private-key
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.2.1
    hooks:
      - id: gitleaks

